### ISSUE TITLE
Performance issue in ie8

### ISSUE THREAD

**Issue by krishnasegu21** [drgullin/icheck#131]
Dear Sir, 

I Venkata working for Qatar Airways. In one of our ASP.NET based web application we are  using iCheck control to show checkbox and radio inputs. It is very good for less number of controls but in one of our web page we have around 250 to 300 checkbox / radio button controls. iCheck is taking a lot of time to load (tested in chrome, safari and ie9) and in IE8 it is not working (getting a script timeout error).

Please advise us and let us know is there any fix to this.

**Comment by drgullin** [comment]
@krishnasegu21 https://github.com/fronteed/iCheck#january-23-2014-v20-release-candidate

You won't get this issue in newer version.

**Comment by krishnasegu21** [comment]
Thanks a lot for your quick reply. I will check and let you know in case of
any issues.

**Comment by drgullin** [comment]
2.x version got a huge performance boost, it works in a much different way, than the 1.x versions.
I've tested it using 1000 radios and checkboxes, works well even on mobile devices (takes ~1 second to customize everything).

2.x rc1 is already safe, it'll be released when I accomplish all mobile tests (such as legacy Android devices and Windows tablets).

The reason why 1.x versions are slow on a huge number of inputs is the events bindings. 2.x version binds only a couple global listeners instead of binding a several ones for the each customized element.
