### ISSUE TITLE
iCheck v2 closest function issue when html not in DOM

### ISSUE THREAD

**Issue by jetheredge** [drgullin/icheck#133]
In your 'closest' function, when the element it is looking for is not found, and the current chunk of html is not yet in the DOM, it throws an error when checking for node.tagName. I added two checks for 'node &&' into the method so that it will stop if it reaches the point where parentNode is null. It seems to work fine where I am using it, do you see any issues with doing this? If not, I'd be happy to submit a pull request.

```
var closest = function(node, tag, className, parent) {
  while (node && node.nodeType !== 9) {
    node = node.parentNode;

    if (node && node.tagName == tag.toUpperCase() && ~node.className.indexOf(className)) {
      parent = node;
      break;
    }
  }

  return parent;
};
```

**Comment by drgullin** [comment]
@jetheredge thanks for the heads up.

I'm not sure about the `while (node && node.nodeType !== 9)`, since there's everytime some node when we call this function. But, we can add this for the specific purpose that doesn't match the standard behavior.

Actually, I haven't tested current version with the elements that aren't currently in the DOM (added to to-do list).
Please submit an issue if you face something not working properly.

You're welcome to submit a pull request.
