### ISSUE TITLE
Doesn't respond to touch in Chrome and Canary on Windows 8

### ISSUE THREAD

**Issue by CalvinDale** [drgullin/icheck#194]
The check boxes and radio buttons aren't responding to touch input (on my Windows 8 system) in both Chrome and Canary.  But the widget are responsive in IE and Firefox.  I have experienced this same behavior with lots of other projects such as [Google's Polymer](http://www.polymer-project.org/) and the [Angular Range-Slider](https://github.com/danielcrisp/angular-rangeslider/issues/16).

**Comment by kshade** [comment]
This problem appears to be fixed in 2.0RC1.

**Comment by ppamrar** [comment]
Checkbox & radio button click not working on following system.
Windows 7, chrome, dell touch screen.

Touch sport is not square or round, we have to touch around square / round.
even not work on label as we use "for" attribute.

**Comment by drgullin** [comment]
iCheck chooses between touch and mouse events to use when initialized. 
It doesn't use both touchstart and mousedown because of the function duplicates, since Chrome fires both events when you touch the screen.
However, this works well in IE, because it supports the pointer events (these are a bit different to regular touch events presented in Chrome). 

iCheck should continue to work in Chrome when you use touch. Because it also relies on the click event.

Chrome doesn't pointer events.
