### ISSUE TITLE
Browser back button

### ISSUE THREAD

**Issue by ghost** [drgullin/icheck#39]
From the tests I have done it looks like if you use the browser back button any selections made are not populated.

Something which is weird as well is that the radio buttons are not populated either, checking the style information on the page submit the buttons are not disabled or hidden so they should be going forward.

I have not been able to track down the issue anyone else come across this?

Revised note it may be an IE issue only?

**Comment by drgullin** [comment]
I've tested across different browsers, this happens only in IE.
Not sure how this issue can be fixed, it doesn't work even if we launch iCheck on `load` event.

Since it's not critical and seems to be specific for IE, I'm closing this issue.
Anyway, it can be fixed by a simple trick - caching the state values in cookies or localstorage.
