### ISSUE TITLE
Change label when checkbox is checked

### ISSUE THREAD

**Issue by KlaasvnA** [drgullin/icheck#69]
I set a labelHoverClass. But I cant find out how to change the label (color) when the checkbox is checked.

**Comment by bocalexandru** [comment]
This would be a good enhancement for this plugin!

**Comment by drgullin** [comment]
You're right, this would be a great feature.

State classes for labels will be available in the next version.

**Comment by KlaasvnA** [comment]
That's great!

**Comment by KlaasvnA** [comment]
Is there a solution I can use in the meantime? I tried it with a .onclick event, but it looks that it doesn't work in combination with the Icheck plugin.

**Comment by shivakumaravula** [comment]
Try using the bind() and apply click event on that. It might work out in your case. I will check that once.

**Comment by KlaasvnA** [comment]
@fronteed: I'm very curious if you implemented the "state classes for labels" yet? If not, could you indicate when it will be available?

Kind Regards!

**Comment by drgullin** [comment]
@KlaasvnA not yet, I'm too busy with my current projects.

**Comment by KlaasvnA** [comment]
@fronteed: That would be great!

**Comment by benjamincharity** [comment]
If you place your label directly next to the checkbox this is possible with minimal CSS using sibling selectors.

Demo: http://jsfiddle.net/XSLtG/

```
label {
    color: red;
}

input:checked + label {
    color: blue;
}
```

Since iCheck is using a div with classes, simply switch out the `:checked` part for the class that you defined within the plugin's options.

Example from a recent project:

```
.form__checkbox {
    [ base element styles ]
}

.form__checkbox.is_checked {
    [ checked styles ]
}

.form__checkbox.is_checked + .form__label {
    [ styles for a label next to a checked input ]
}

.form__checkbox.is_disabled {
    [ disabled styles ]
}

.form__checkbox.is_disabled + .form__label {
    [ styles for a label next to a disabled input ]
}
```

A javascript solution still might be a good idea as many people nest checkbox/radio inputs inside the `<label>` rendering the above solution moot.

**Comment by KlaasvnA** [comment]
@benjamincharity: Great it works! Thanks a Lot!

I think I only tried:  input:checked + label    

instead of:  .icheckbox_minimal.checked + label.

**Comment by drgullin** [comment]
2.x version is on the way https://github.com/fronteed/iCheck/tree/2.x-beta

iCheck will support a `mirror` option out of the box.

`+` selector is a right solution, but the `mirror` option may be needed when label and input tags aren't placed at the same level in the dom tree.

Options that will be supported:
- checkedLabelClass
- disabledLabelClass
- indeterminateLabelClass
- hoverLabelClass
- focusLabelClass
- activeLabelClass

`labelHover` will be replaced with a `mirror` option. If `true`, a mirror classes will be toggled between label and input tags.

iCheck won't support options like `uncheckedLabelClass` and `enabledLabelRadioClass`, since they are too specific.

**Comment by drgullin** [comment]
```
checkedLabelClass
disabledLabelClass
indeterminateLabelClass
hoverLabelClass
focusLabelClass
activeLabelClass
```

iCheck 2.x now supports these options.
